export const sample_foods = [
  {
    id: "1",
    name: "Pizza ",
    cookTime: "10-20",
    price: 200,
    favorite: false,
    origins: ["italy"],
    stars: 4.5,
    imageUrl: "food-1.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
  {
    id: "2",
    name: "Meatball",
    price: 210,
    cookTime: "20-30",
    favorite: true,
    origins: ["persia", "china"],
    stars: 5,
    imageUrl: "food-2.jpg",
    tags: ["SlowFood", "Lunch"],
  },
  {
    id: "3",
    name: "Burger",
    price: 100,
    cookTime: "10-15",
    favorite: false,
    origins: ["germany", "us"],
    stars: 3.5,
    imageUrl: "food-3.jpg",
    tags: ["FastFood", "Burger"],
  },
  {
    id: "4",
    name: "Fried Potatoes",
    price: 110,
    cookTime: "15-20",
    favorite: true,
    origins: ["belgium", "france"],
    stars: 3,
    imageUrl: "food-4.jpg",
    tags: ["FastFood", "Fried"],
  },
  {
    id: "5",
    name: "Chicken Soup",
    price: 300,
    cookTime: "40-50",
    favorite: false,
    origins: ["india", "asia"],
    stars: 3.5,
    imageUrl: "food-5.jpg",
    tags: ["SlowFood", "Soup"],
  },
  {
    id: "6",
    name: "Vegetables Pizza",
    price: 120,
    cookTime: "40-50",
    favorite: false,
    origins: ["italy"],
    stars: 4.0,
    imageUrl: "food-6.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
  {
    id: "7",
    name: "Noodles",
    price: 150,
    cookTime: "30-35",
    favorite: false,
    origins: ["china"],
    stars: 4.0,
    imageUrl: "food-7.jpg",
    tags: ["FastFood", "Noodles", "Lunch"],
  },
  {
    id: "8",
    name: "Fried Chicken",
    price: 180,
    cookTime: "30-35",
    favorite: true,
    origins: ["italy"],
    stars: 4.2,
    imageUrl: "food-8.jpg",
    tags: ["FastFood", "Fried Chicken", "Fried", "Lunch"],
  },
];

export const sample_tags = [
  { name: "All", count: 8 },
  { name: "FastFood", count: 5 },
  { name: "Pizza", count: 2 },
  { name: "Lunch", count: 5 },
  { name: "SlowFood", count: 2 },
  { name: "Burger", count: 1 },
  { name: "Fried", count: 2 },
  { name: "Soup", count: 1 },
];
